# Creates a RabbitMQ cluster with 3 nodes using docker.
# Can be used for Extensions Development and Transformers Tool
# @author: abey.tom@appdynamics.com

rabbit1:
  image: extensions/rabbitmq
  hostname: rabbit1
  ports:
    - "5672:5672"
    - "15672:15672"

rabbit2:
  image: extensions/rabbitmq
  hostname: rabbit2
  links:
    - rabbit1
  environment: 
   - CLUSTERED=true
   - CLUSTER_WITH=rabbit1
   - RAM_NODE=true
  ports:
      - "5673:5672"
      - "15673:15672"

rabbit3:
  image: extensions/rabbitmq
  hostname: rabbit3
  links:
    - rabbit1
    - rabbit2
  environment: 
   - CLUSTERED=true
   - CLUSTER_WITH=rabbit1   
  ports:
        - "5674:5672"
